Repository euclid-lyc/lyc-frontend, pull requests merged in 2025-02, with the labels that each got.

#144 [Modify} hsh/143 modify find id pw screen
  lyc_flutter_project/lib/auth/find_id/model/member_model.dart
  lyc_flutter_project/lib/auth/find_id/model/member_model.g.dart
  lyc_flutter_project/lib/auth/find_id/provider/find_id_provider.dart
  lyc_flutter_project/lib/auth/find_id/provider/send_email_provider.dart
  lyc_flutter_project/lib/auth/find_id/repository/find_id_repository.dart
  lyc_flutter_project/lib/auth/find_id/repository/find_id_repository.g.dart
  lyc_flutter_project/lib/auth/find_id/screens/find_id_screen_1.dart
  lyc_flutter_project/lib/auth/find_id/screens/find_id_screen_2.dart
  lyc_flutter_project/lib/auth/find_id/screens/find_id_screen_3.dart
  lyc_flutter_project/lib/auth/find_pw/provider/find_pw_provider.dart
  lyc_flutter_project/lib/auth/find_pw/repository/find_pw_repository.dart
  lyc_flutter_project/lib/auth/find_pw/repository/find_pw_repository.g.dart
  lyc_flutter_project/lib/auth/find_pw/screens/find_password_screen_1.dart
  lyc_flutter_project/lib/auth/find_pw/screens/find_password_screen_2.dart
  lyc_flutter_project/lib/auth/find_pw/screens/find_password_screen_3.dart
  lyc_flutter_project/lib/auth/find_pw/screens/find_password_screen_4.dart
  lyc_flutter_project/lib/auth/find_pw/screens/find_pw_screen_1.dart
  lyc_flutter_project/lib/auth/find_pw/screens/find_pw_screen_2.dart
  lyc_flutter_project/lib/auth/find_pw/screens/find_pw_screen_3.dart
  lyc_flutter_project/lib/auth/find_pw/screens/find_pw_screen_4.dart
  lyc_flutter_project/lib/auth/join/screens/login_screen.dart
  lyc_flutter_project/lib/commissions/screen/basic_info_screen.dart
  lyc_flutter_project/lib/commissions/screen/desired_style_screen.dart
  lyc_flutter_project/lib/common/widget/custom_input_field.dart
  lyc_flutter_project/lib/common/widget/custom_next_button.dart
  lyc_flutter_project/lib/common/widget/social_login_buttons.dart
  lyc_flutter_project/lib/main.dart
  lyc_flutter_project/lib/mypage/widget/select_buttons_in_posting.dart
Labels: ✏️ Modify, 🛠️ Fix, ♻️ Refactor

#149 [Fix] hsh/148 fix merge error clear
  lyc_flutter_project/lib/auth/find_pw/repository/find_pw_repository.dart
  lyc_flutter_project/lib/auth/find_pw/screens/find_pw_screen_3.dart
  lyc_flutter_project/lib/auth/join/screens/login_screen.dart
Labels: 🛠️ Fix

#154 [152] Doyeon/152 modify new api for feed screen
  lyc_flutter_project/android/app/.cxx/Debug/31411717/arm64-v8a/.cmake/api/v1/reply/index-2025-02-15T08-28-31-0697.json
  lyc_flutter_project/android/app/.cxx/Debug/31411717/arm64-v8a/.cmake/api/v1/reply/index-2025-02-23T12-04-58-0187.json
  lyc_flutter_project/android/app/.cxx/Debug/31411717/arm64-v8a/CMakeFiles/3.22.1-g37088a8-dirty/CMakeSystem.cmake
  lyc_flutter_project/android/app/.cxx/Debug/31411717/arm64-v8a/configure_fingerprint.bin
  lyc_flutter_project/android/app/.cxx/Debug/31411717/armeabi-v7a/.cmake/api/v1/reply/index-2025-02-15T08-28-33-0114.json
  lyc_flutter_project/android/app/.cxx/Debug/31411717/armeabi-v7a/.cmake/api/v1/reply/index-2025-02-23T12-05-02-0960.json
  lyc_flutter_project/android/app/.cxx/Debug/31411717/armeabi-v7a/CMakeFiles/3.22.1-g37088a8-dirty/CMakeSystem.cmake
  lyc_flutter_project/android/app/.cxx/Debug/31411717/armeabi-v7a/configure_fingerprint.bin
  lyc_flutter_project/android/app/.cxx/Debug/31411717/x86/.cmake/api/v1/reply/index-2025-02-15T08-28-34-0554.json
  lyc_flutter_project/android/app/.cxx/Debug/31411717/x86/.cmake/api/v1/reply/index-2025-02-23T12-05-07-0215.json
  lyc_flutter_project/android/app/.cxx/Debug/31411717/x86/CMakeFiles/3.22.1-g37088a8-dirty/CMakeSystem.cmake
  lyc_flutter_project/android/app/.cxx/Debug/31411717/x86/configure_fingerprint.bin
  lyc_flutter_project/android/app/.cxx/Debug/31411717/x86_64/.cmake/api/v1/reply/index-2025-02-15T08-28-35-0878.json
  lyc_flutter_project/android/app/.cxx/Debug/31411717/x86_64/.cmake/api/v1/reply/index-2025-02-23T12-05-11-0329.json
  lyc_flutter_project/android/app/.cxx/Debug/31411717/x86_64/CMakeFiles/3.22.1-g37088a8-dirty/CMakeSystem.cmake
  lyc_flutter_project/android/app/.cxx/Debug/31411717/x86_64/configure_fingerprint.bin
  lyc_flutter_project/lib/auth/find_id/repository/find_id_repository.g.dart
  lyc_flutter_project/lib/auth/find_pw/repository/find_pw_repository.g.dart
  lyc_flutter_project/lib/director/repository/director_repository.g.dart
  lyc_flutter_project/lib/feed/provider/feed_provider.dart
  lyc_flutter_project/lib/feed/repository/feed_repository.dart
  lyc_flutter_project/lib/feed/repository/feed_repository.g.dart
  lyc_flutter_project/lib/feed/repository/weather_repository.dart
  lyc_flutter_project/lib/feed/repository/weather_repository.g.dart
  lyc_flutter_project/lib/feed/screen/feed_screen.dart
  lyc_flutter_project/lib/mypage/repository/mypage_repository.g.dart
  lyc_flutter_project/lib/posting/repository/clothes_repository.g.dart
  lyc_flutter_project/lib/posting/repository/coordi_repository.g.dart
  lyc_flutter_project/lib/setting/repository/setting_repository.g.dart
Labels: ✏️ Modify
